### ISSUE TITLE
Create list of jar dependencies used by the various bits of the various modules

### ISSUE THREAD

**Issue by vietj** [vert-x3/eclipse-proposal-wip#1]

**Comment by cescoffier** [comment]
Will generate the dependency graph.

(Aether, my love.... ;-))

**Comment by cescoffier** [comment]
According to the use case, it's a macro-analysis of the dependencies (for each modules, what are the set of dependencies, what is the set of provided artifacts).

**Comment by karianna** [comment]
You might want to look at the Ning dependeny analyser plugin as well..

On Thursday, 17 December 2015, Clement Escoffier notifications@github.com
wrote:

> According to the use case, it's a macro-analysis of the dependencies (for
> each modules, what are the set of dependencies, what is the set of provided
> artifacts).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vert-x3/eclipse-proposal-wip/issues/1#issuecomment-165377702
> .

## 

Cheers, Martijn (Sent from Gmail Mobile)
